会場をインプレスに変更
yayoiw/ichiyasaGitSample pull request #1
Opened 2022-12-20 11:17 UTC by yayoiw

###変更内容
会場を株式会社インプレスに変更
###背景
株式会社インプレスが会場を艇庫湯してくださることになった

2022-12-20 16:09 UTC, 841test commented
問題ないのでマージします

2022-12-21 14:33 UTC, 841test commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
テスト

2022-12-21 14:39 UTC, 841test requested changes

2022-12-21 14:39 UTC, 841test commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
test

2022-12-21 14:41 UTC, yayoiw commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
fixed

2022-12-21 14:43 UTC, 841test approved these changes

2022-12-21 14:57 UTC, merged